#pragma kernel CSGenerator

#include "/Includes/Volume.compute"
#include "/Includes/Tables.compute"

static uint2 oa[3] = 
{
	uint2(1,2),
	uint2(0,2),
	uint2(0,1)
};

int3 chunkOffset;

float floorLevel;

[numthreads(8,8,1)]
void CSGenerator(uint3 id : SV_DispatchThreadID)
{
	int index = getVolumeIndex(id);

	IsoPoint p;
	p.dist = float(id.y) - floorLevel;
	p.normal = float3(0, sign(p.dist), 0);

	iso[index] = p;
}
